version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: wordpress
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DB=test_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8080:80"
    container_name: wordpress
  mysql:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test_db
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3307:3306"
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    links:
      - mysql
    environment:
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - /sessions
    container_name: phpmyadmin
volumes:
  mysql_volume:
